"""Add description

Revision ID: 171867c3ff4d
Revises: e7a1c9d4b2f8
Create Date: 2026-08-26 17:20:24.484828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171867c3ff4d'
down_revision: Union[str, Sequence[str], None] = 'e7a1c9d4b2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain_fields', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain_fields', 'description')
    # ### end Alembic commands ###
