"""new tables

Revision ID: 823ae9216d22
Revises: 171867c3ff4d
Create Date: 2026-08-29 16:41:38.455002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823ae9216d22'
down_revision: Union[str, Sequence[str], None] = '171867c3ff4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=50), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_model', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_extraction_status'), 'documents', ['extraction_status'], unique=False)
    op.create_index('uq_documents_content_hash_active', 'documents', ['content_hash'], unique=True, postgresql_where=Text(length='deleted_at IS NULL'))
    op.create_table('report_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('linked_by', sa.String(length=36), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'report_id', name='uq_doc_report')
    )
    op.create_index(op.f('ix_report_documents_document_id'), 'report_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_report_documents_report_id'), 'report_documents', ['report_id'], unique=False)
    op.create_table('report_locks',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('locked_by', sa.String(length=36), nullable=True),
    sa.Column('lock_token', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('mapping_in_progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('report_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('linked_by', sa.String(length=36), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'user_id', name='uq_report_user')
    )
    op.create_index(op.f('ix_report_users_report_id'), 'report_users', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_users_user_id'), 'report_users', ['user_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_report_id'), 'share_links', ['report_id'], unique=False)
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=True)
    op.add_column('evidence', sa.Column('document_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_evidence_document_id'), 'evidence', ['document_id'], unique=False)
    op.create_foreign_key(None, 'evidence', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.add_column('reports', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('reports', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_reports_deleted_at'), 'reports', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'reports', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_deleted_at'), table_name='reports')
    op.drop_column('reports', 'created_by')
    op.drop_column('reports', 'deleted_at')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_document_id'), table_name='evidence')
    op.drop_column('evidence', 'document_id')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_report_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_report_users_user_id'), table_name='report_users')
    op.drop_index(op.f('ix_report_users_report_id'), table_name='report_users')
    op.drop_table('report_users')
    op.drop_table('report_locks')
    op.drop_index(op.f('ix_report_documents_report_id'), table_name='report_documents')
    op.drop_index(op.f('ix_report_documents_document_id'), table_name='report_documents')
    op.drop_table('report_documents')
    op.drop_index('uq_documents_content_hash_active', table_name='documents', postgresql_where=Text(length='deleted_at IS NULL'))
    op.drop_index(op.f('ix_documents_extraction_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
