"""create new tables

Revision ID: d1ed80e24fc0
Revises: a1b2c3d4e5f6
Create Date: 2026-08-21 16:28:39.422145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ed80e24fc0'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_domain_name')
    )
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_table('domain_manifests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('section_count', sa.Integer(), nullable=True),
    sa.Column('field_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'version', name='uq_domain_manifest_version')
    )
    op.create_index(op.f('ix_domain_manifests_domain_id'), 'domain_manifests', ['domain_id'], unique=False)
    op.create_index(op.f('ix_domain_manifests_id'), 'domain_manifests', ['id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'name', name='uq_prompt_domain_name')
    )
    op.create_index(op.f('ix_prompts_domain_id'), 'prompts', ['domain_id'], unique=False)
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    op.create_table('domain_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifest_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manifest_id'], ['domain_manifests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manifest_id', 'name', name='uq_domain_section_name')
    )
    op.create_index(op.f('ix_domain_sections_id'), 'domain_sections', ['id'], unique=False)
    op.create_index(op.f('ix_domain_sections_manifest_id'), 'domain_sections', ['manifest_id'], unique=False)
    op.create_table('domain_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['domain_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'name', name='uq_domain_field_name')
    )
    op.create_index(op.f('ix_domain_fields_id'), 'domain_fields', ['id'], unique=False)
    op.create_index(op.f('ix_domain_fields_section_id'), 'domain_fields', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_fields_section_id'), table_name='domain_fields')
    op.drop_index(op.f('ix_domain_fields_id'), table_name='domain_fields')
    op.drop_table('domain_fields')
    op.drop_index(op.f('ix_domain_sections_manifest_id'), table_name='domain_sections')
    op.drop_index(op.f('ix_domain_sections_id'), table_name='domain_sections')
    op.drop_table('domain_sections')
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_domain_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_domain_manifests_id'), table_name='domain_manifests')
    op.drop_index(op.f('ix_domain_manifests_domain_id'), table_name='domain_manifests')
    op.drop_table('domain_manifests')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
